"""Initial migration.

Revision ID: 1da50dd7c16d
Revises: 8096f179f3e2
Create Date: 2022-08-20 11:42:25.298179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da50dd7c16d'
down_revision = '8096f179f3e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_picture')
    # ### end Alembic commands ###
