"""users updated

Revision ID: 9f8e6abc95e5
Revises: 7d2ec0d9c348
Create Date: 2022-08-20 16:46:49.079335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8e6abc95e5'
down_revision = '7d2ec0d9c348'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'currency')
    # ### end Alembic commands ###
