"""Initial migration.

Revision ID: a03538757b24
Revises: 
Create Date: 2022-08-20 11:30:48.997757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03538757b24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('days', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('state', sa.String(), nullable=True))
    op.add_column('items', sa.Column('departure_date', sa.String(), nullable=True))
    op.add_column('items', sa.Column('total_seats', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image')
    op.drop_column('users', 'name')
    op.drop_column('items', 'total_seats')
    op.drop_column('items', 'departure_date')
    op.drop_column('items', 'state')
    op.drop_column('items', 'days')
    # ### end Alembic commands ###
