"""merchant_id added

Revision ID: bde9af43baf3
Revises: 9f8e6abc95e5
Create Date: 2022-08-20 17:05:45.974328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde9af43baf3'
down_revision = '9f8e6abc95e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checkouts', type_='foreignkey')
    op.drop_column('checkouts', 'item_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkouts', sa.Column('item_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'checkouts', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
